//signin constants
export const authStatic = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  SIGNUP_REQUEST:"SIGNUP_REQUEST",
  SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
  SIGNUP_FAILURE:"SIGNUP_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  EMAIL_VERIFICATION_REQUEST: "EMAIL_VERIFICATION_REQUEST",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILURE: "EMAIL_VERIFICATION_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  GET_ALL_ADMINS_REQUEST:"GET_ALL_ADMINS_REQUEST",
  GET_ALL_ADMINS_SUCCESS:"GET_ALL_ADMINS_SUCCESS",
  GET_ALL_ADMINS_FAILURE:"GET_ALL_ADMINS_FAILURE",

  EDIT_ADMIN_REQUEST:"EDIT_ADMIN_REQUEST",
  EDIT_ADMIN_SUCCESS:"EDIT_ADMIN_SUCCESS",
  EDIT_ADMIN_FAILURE:"EDIT_ADMIN_FAILURE",

  GET_ALL_ROLES_REQUEST:"GET_ALL_ROLES_REQUEST",
  GET_ALL_ROLES_SUCCESS:"GET_ALL_ROLES_SUCCESS",
  GET_ALL_ROLES_FAILURE:"GET_ALL_ROLES_FAILURE",

  CREATE_NEW_ROLE_REQUEST:"CREATE_NEW_ROLE_REQUEST",
  CREATE_NEW_ROLE_SUCCESS:"CREATE_NEW_ROLE_SUCCESS",
  CREATE_NEW_ROLE_FAILURE:"CREATE_NEW_ROLE_FAILURE",

  EDIT_ACCESS_REQUEST:"EDIT_ACCESS_REQUEST",
  EDIT_ACCESS_SUCCESS:"EDIT_ACCESS_SUCCESS",
  EDIT_ACCESS_FAILURE:"EDIT_ACCESS_FAILURE",

  GET_SPECIFIC_ROLE_REQUEST:"GET_SPECIFIC_ROLE_REQUEST",
  GET_SPECIFIC_ROLE_SUCCESS:"GET_SPECIFIC_ROLE_SUCCESS",
  GET_SPECIFIC_ROLE_FAILURE:"GET_SPECIFIC_ROLE_FAILURE",
};
// <---------------------Business and Users Fetch constants-------------------------->

// Business MONTH constants
export const businessStatic = {
  BUSINESS_FETCH_MONTH_DATA_REQUEST: "BUSINESS_FETCH_MONTH_DATA_REQUEST",
  BUSINESS_FETCH_MONTH_DATA_SUCCESS: "BUSINESS_FETCH_MONTH_DATA_SUCCESS",
  BUSINESS_FETCH_MONTH_DATA_FAILURE: "BUSINESS_FETCH_MONTH_DATA_FAILURE",
};

// Business  constants
export const businessListStatic = {
  BUSINESS_DATA_REQUEST: "BUSINESS_DATA_REQUEST",
  BUSINESS_DATA_SUCCESS: "BUSINESS_DATA_SUCCESS",
  BUSINESS_DATA_FAILURE: "BUSINESS_DATA_FAILURE",
};

//<---------------------Delete Business contants------------------>
export const deleteBusinessStatic = {
  DELETE_BUSINESS_USERS_REQUEST: "DELETE_BUSINESS_USERS_REQUEST",
  DELETE_BUSINESS_USERS_SUCCESS: "DELETE_BUSINESS_USERS_SUCCESS",
  DELETE_BUSINESS_USERS_FAILURE: "DELETE_BUSINESS_USERS_FAILURE",
};
// <-------------------Block Unblock constants-------------------->
export const blockUnblockBusinessStatic = {
  BLOCK_UNBLOCK_BUSINESS_USERS_REQUEST: "BLOCK_UNBLOCK_BUSINESS_USERS_REQUEST",
  BLOCK_UNBLOCK_BUSINESS_USERS_SUCCESS: "BLOCK_UNBLOCK_BUSINESS_USERS_SUCCESS",
  BLOCK_UNBLOCK_BUSINESS_USERS_FAILURE: "BLOCK_UNBLOCK_BUSINESS_USERS_FAILURE",
};
// <----------------USER--------------->
// USER  constants
export const userStatic = {
  USER_FETCH_MONTH_DATA_REQUEST: "USER_FETCH_MONTH_DATA_REQUEST",
  USER_FETCH_MONTH_DATA_SUCCESS: "USER_FETCH_MONTH_DATA_SUCCESS",
  USER_FETCH_MONTH_DATA_FAILURE: "USER_FETCH_MONTH_DATA_FAILURE",
};
// USER  constants
export const userListStatic = {
  USER_DATA_REQUEST: "USER_DATA_REQUEST",
  USER_DATA_SUCCESS: "USER_DATA_SUCCESS",
  USER_DATA_FAILURE: "USER_DATA_FAILURE",
};
//<---------------------Delete Users contants------------------>
export const deleteUserStatic = {
  DELETE_USERS_REQUEST: "DELETE_USERS_REQUEST",
  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
  DELETE_USERS_FAILURE: "DELETE_USERS_FAILURE",
};

// <-------------------Block Unblock  Userconstants-------------------->
export const blockUnblockUserStatic = {
  BLOCK_UNBLOCK_USERS_REQUEST: "BLOCK_UNBLOCK_USERS_REQUEST",
  BLOCK_UNBLOCK_USERS_SUCCESS: "BLOCK_UNBLOCK_USERS_SUCCESS",
  BLOCK_UNBLOCK_USERS_FAILURE: "BLOCK_UNBLOCK_USERS_FAILURE",
};

// <------------------------Day wise constants----------------------->
export const daywiseConstants={
  DAY_WISE_STATIC_REQUEST:"DAY_WISE_STATIC_REQUEST",
  DAY_WISE_STATIC_SUCCESS:"DAY_WISE_STATIC_SUCCESS",
  DAY_WISE_STATIC_FAILURE:"DAY_WISE_STATIC_FAILURE"
}

//<--------------------------------CATEGORIES--------------------------------------->

//<----------------GET ALL CATEGORIES-------------------------------->
export const getAllCategoryStatic = {
  GET_ALL_CATEGORIES_STATIC_REQUEST: "GET_ALL_CATEGORIES_STATIC_REQUEST",
  GET_ALL_CATEGORIES_STATIC_SUCCESS: "GET_ALL_CATEGORIES_STATIC_SUCCESS",
  GET_ALL_CATEGORIES_STATIC_FAILURE: "GET_ALL_CATEGORIES_STATIC_FAILURE",
};
// delete categories
export const deleteCategoryStatic = {
  DELETE_CATEGORY_STATIC_REQUEST: "DELETE_CATEGORY_STATIC_REQUEST",
  DELETE_CATEGORY_STATIC_SUCCESS: "DELETE_CATEGORY_STATIC_SUCCESS",
  DELETE_CATEGORY_STATIC_FAILURE: "DELETE_CATEGORY_STATIC_FAILURE",
};

// Update categories
export const updateCategoryStatic = {
  UPDATE_CATEGORY_STATIC_REQUEST: "UPDATE_CATEGORY_STATIC_REQUEST",
  UPDATE_CATEGORY_STATIC_SUCCESS: "UPDATE_CATEGORY_STATIC_SUCCESS",
  UPDATE_CATEGORY_STATIC_FAILURE: "UPDATE_CATEGORY_STATIC_FAILURE",
};

// Update categories
export const createCategoryStatic = {
  CREATE_CATEGORY_STATIC_REQUEST: "CREATE_CATEGORY_STATIC_REQUEST",
  CREATE_CATEGORY_STATIC_SUCCESS: "CREATE_CATEGORY_STATIC_SUCCESS",
  CREATE_CATEGORY_STATIC_FAILURE: "CREATE_CATEGORY_STATIC_FAILURE",
};

// Update categories
export const categoryStatsStatic = {
  CATEGORY_STATS_STATIC_REQUEST: "CATEGORY_STATS_STATIC_REQUEST",
  CATEGORY_STATS_STATIC_SUCCESS: "CATEGORY_STATS_STATIC_SUCCESS",
  CATEGORY_STATS_STATIC_FAILURE: "CATEGORY_STATS_STATIC_FAILURE",
};



// <-------------------------------------ADmin Specific------------------------------------>

//get business queries
export const businessQueriesStatic={
  BUSINESS_QUERIES_STATIC_REQUEST:"BUSINESS_QUERIES_STATIC_REQUEST",
  BUSINESS_QUERIES_STATIC_SUCCESS:"BUSINESS_QUERIES_STATIC_SUCCESS",
  BUSINESS_QUERIES_STATIC_FAILURE:"BUSINESS_QUERIES_STATIC_FAILURE"

}
//Update business queries
export const updateBusinessQueriesStatic={
  UPDATE_BUSINESS_QUERIES_STATIC_REQUEST:"UPDATE_BUSINESS_QUERIES_STATIC_REQUEST",
  UPDATE_BUSINESS_QUERIES_STATIC_SUCCESS:"UPDATE_BUSINESS_QUERIES_STATIC_SUCCESS",
  UPDATE_BUSINESS_QUERIES_STATIC_FAILURE:"UPDATE_BUSINESS_QUERIES_STATIC_FAILURE"

}

//get Users queries
export const usersQueriesStatic={
  USER_QUERIES_STATIC_REQUEST:"USER_QUERIES_STATIC_REQUEST",
  USER_QUERIES_STATIC_SUCCESS:"USER_QUERIES_STATIC_SUCCESS",
  USER_QUERIES_STATIC_FAILURE:"USER_QUERIES_STATIC_FAILURE"

}
//Update Users queries
export const updateUsersQueriesStatic={
  UPDATE_USER_QUERIES_STATIC_REQUEST:"UPDATE_USER_QUERIES_STATIC_REQUEST",
  UPDATE_USER_QUERIES_STATIC_SUCCESS:"UPDATE_USER_QUERIES_STATIC_SUCCESS",
  UPDATE_USER_QUERIES_STATIC_FAILURE:"UPDATE_USER_QUERIES_STATIC_FAILURE"

}